HardwareSerial: make begin/end methods pure-virtual
Doesn't have any practical effect, but fixes 'undefined reference to
vtable for HardwareSerial' link error when compiling with -O0.

For science: the neostrip demo program is 17004 bytes when compiled with
-Os -flto, but 39908 bytes when compiled with -O0, a 57% reduction!

Note: I could also remove the 'using Print::write' statements from
HardwareSerial and Uart since the Print::write methods are already
public, but I'll leave them to reduce patch size.